In [14]:
from tensorflow.keras.models import load_model
import tensorflow as tf
from tensorflow import keras
%matplotlib inline
import numpy as np
import pickle
import cv2
from os import listdir
from sklearn.preprocessing import LabelBinarizer
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D, BatchNormalization
from tensorflow.keras import backend as K
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model

In [15]:
model = load_model("model_algae_ped.h5")

In [17]:
EPOCHS = 25
INIT_LR = 1e-3
BS = 15
default_image_size = tuple((256, 256))
image_size = 0
width=256
height=256
depth=3
opt = Adam(lr=INIT_LR, decay=INIT_LR / EPOCHS)
model.compile(loss="categorical_crossentropy", optimizer=opt,metrics=["accuracy"])


In [18]:
class MyCustomCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}): 
        if(logs.get('acc') >= 0.96):   
            print("Reached 95% accuracy so cancelling training!")
            self.model.stop_training = True

In [19]:
EPOCHS = 25
INIT_LR = 1e-3
BS = 15
default_image_size = tuple((256, 256))
image_size = 0
width=256
height=256
depth=3
#train_dir=r"C:\Users\Glau\Desktop\DP\Single_fifteen\Train"
valid_dir=r"C:\Users\Glau\Desktop\DP\Pediastrum_cnn\Test"
#train_folder=listdir(train_dir)
valid_folder=listdir(valid_dir)

In [20]:
def convert_image_to_array(image_dir):
    try:
        image = cv2.imread(image_dir)
        if image is not None :
            image = cv2.resize(image, default_image_size)   
            return img_to_array(image)
        else :
            return np.array([])
    except Exception as e:
        print(f"Error : {e}")
        return None

In [21]:
callbacks = MyCustomCallback()

In [22]:
valid_image_list, valid_image_label= [], []
for disease_folder in valid_folder:
    print(f"processing {disease_folder} ...")
    disease_img_folder= listdir(f"{valid_dir}/{disease_folder}")

    for disease_img in disease_img_folder:
    #for disease_img in disease_img_folder[: : 2]: 
        image_directory = f"{valid_dir}/{disease_folder}/{disease_img}"
        if image_directory.endswith(".jpg") == True or image_directory.endswith(".TIFF") == True:
            valid_image_list.append(convert_image_to_array(image_directory))
            valid_image_label.append(disease_folder)
print("[INFO] Image loading completed")

processing Lacunastrum gracilimum ...
processing Monactinus simplex ...
processing Parapediastrum biradiatum ...
processing Pediastrum angulosum ...
processing Pediastrum duplex ...
processing Pseudopediastrum boryanum ...
processing Stauridium tetras ...
[INFO] Image loading completed


In [23]:
print(len(valid_image_label))

8400


In [24]:
label_binarizer = LabelBinarizer()
#bin_train_image_labels = label_binarizer.fit_transform(train_image_label)
bin_valid_image_labels = label_binarizer.fit_transform(valid_image_label)
pickle.dump(label_binarizer,open('Label_Instance.pk2', 'wb'))
n_classes = len(label_binarizer.classes_)

In [25]:
print(len(bin_valid_image_labels))


8400


In [26]:
for i in bin_valid_image_labels:
    print(i)

[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0

[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0 0 0 0]
[0 1 0 0

[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0 0 0 0]
[0 0 1 0

[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0 1 0 0]
[0 0 0 0

[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 0]
[0 0 0 0

In [27]:
np_valid_image_list = np.array(valid_image_list, dtype=np.float16) / 255.0

In [29]:
ycalculated = model.predict(np_valid_image_list)


UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_2/conv2d_550/Conv2D (defined at c:\users\glau\.conda\envs\himanshu\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_64911]

Function call stack:
distributed_function


In [ ]:
print(ycalculated[1])

In [ ]:
yhat_classes =np.argmax(ycalculated,axis=1)

In [ ]:
print(yhat_classes)

In [ ]:
import numpy as np
rounded_labels=np.argmax(bin_valid_image_labels,axis=1)

In [ ]:
print(len(rounded_labels))

In [ ]:
print(bin_val_image_labels)

In [ ]:
ffrom sklearn.metrics import accuracy_score 
from sklearn.metrics import precision_score 
from sklearn.metrics import recall_score 
from sklearn.metrics import f1_score 
from sklearn.metrics import cohen_kappa_score 
from sklearn.metrics import roc_auc_score 
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import Normalizer
#import seaborn as sns
#y_pred=model.predict_classes(np_valid_image_list)
#con_mat = tf.math.confusion_matrix(labels=y_true, predictions=ycalculated).numpy()
#matrix = confusion_matrix(rounded_labels,yhat_classes)
#y_pred=model.predict(np.array(val_image_list))
cm =confusion_matrix(bin_valid_image_labels,yhat_classes)  

#matrix =confusion_matrix(bin_val_image_labels.argmax(axis=1), ycalculated)
#print(matrix)

In [ ]:
print(np.nonzero(matrix[0]))

In [ ]:
accuracy = accuracy_score(rounded_labels, yhat_classes)
print('Accuracy: %f' % accuracy)

In [ ]:
yhat_probs = model.predict(np_valid_image_list, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(testX, verbose=0)